baffle:
  data:
    filename: /data.json
    check-method: false
  forward:
    address: 20.208.28.73:9021,20.208.28.131:9021,20.208.27.147:9021,20.208.14.186:9021
    connect:
      timeout: 3000
    read:
      timeout: 3000
  global:
    mode: file
  enable:
    inbound-links: true