baffle:
  data:
    filename: /data.json
    check-method: false
  forward:
    address: localhost:8080
    connect:
      timeout: 2000
    read:
      timeout: 2000
  global:
    timeout: 5000
    mode: file
  enable:
    inbound-links: true