baffle:
  data:
    filename: /data.json
    check-method: false
  forward:
    address: 20.208.28.73:9021,20.208.28.131:9021,20.208.27.147:9021,20.208.14.186:9021
    connect:
      timeout: 2000
    read:
      timeout: 2000
  global:
    timeout: 5000
    mode: file
    http:
      wait: 10
  enable:
    inbound-links: true
  http:
    wait:
      uri-map: '{ "/a": 10000, "/b": 200 }'